version: '2'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toot
      MYSQL_DATABASE: newsy
    volumes:
      - ./db-setup/:/docker-entrypoint-initdb.d/
    ports:
      - "3309:3306"
    expose:
      - "3306"
  jenkins:
    image: jenkins
    volumes:
      - ./jenkins_home/:/var/jenkins_home
    ports:
      - "8085:8080"
      - "50000:50000"
    links:
      - gogs
      - sonarqube
  gogs:
    image: gogs/gogs
    # mounting starts generating errors on windows :(
    volumes:
      - ./gogs_home/git:/data/git
      - ./gogs_home/gogs:/data/gogs
    ports:
      - "10022:22"
      - "10080:3000"
    expose:
      - "3000"
    links:
      - db
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"