version: '2'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: toot
      MYSQL_DATABASE: newsy
    volumes:
      - ./newsy-db-setup/:/docker-entrypoint-initdb.d/
    ports:
      - "3309:3306"